#!/usr/bin/env python3

a = 'Hello World This is real Cool'

print("Content-type: text/html")
print()
print("<!DOCTYPE html>")
print()
print("<html lang="en">")
print()
print("<head>")
print()
print("<meta charset="UTF-8">")
print()
print("<title>Document</title>")
print()
print("</head>")
print()
print('<body>')
print('<table {border: 2px solid black; border-collapse: collapse;} >')
print()
print('<tr {border: 2px solid black;}>')
print()
print('<td {border: 2px solid black;}>',a,'</td>')
print()
print('<td {border: 2px solid black;}>',a,'</td>')
print()
print('<td {border: 2px solid black;}>',a,'</td>')
print()
print('</tr>')
print('</table>')
print('</body>')
